const people = [
    {
        id: 1,
        first_name: 'Kaylil',
        last_name: 'Hovey',
        email: 'khovey0@gizmodo.com',
        gender: 'Female',
        ip_address: '128.158.239.223',
        title: 'Rev',
        job_title: 'Recruiting Manager',
        race: 'Vietnamese',
        company: 'Browseblab',
        age: 33
    },
    {
        id: 2,
        first_name: 'Cesare',
        last_name: 'Caroline',
        email: 'ccaroline1@tmall.com',
        gender: 'Male',
        ip_address: '7.78.224.248',
        title: 'Rev',
        job_title: 'Computer Systems Analyst II',
        race: 'Black or African American',
        company: 'Wordtune',
        age: 50
    },
    {
        id: 3,
        first_name: 'Xaviera',
        last_name: 'Danilchenko',
        email: 'xdanilchenko2@so-net.ne.jp',
        gender: 'Female',
        ip_address: '161.223.97.94',
        title: 'Mr',
        job_title: 'Statistician IV',
        race: 'Asian',
        company: 'Rhynyx',
        age: 55
    },
    {
        id: 4,
        first_name: 'Shandy',
        last_name: 'Sanford',
        email: 'ssanford3@uiuc.edu',
        gender: 'Female',
        ip_address: '40.218.230.208',
        title: 'Honorable',
        job_title: 'Data Coordiator',
        race: 'Eskimo',
        company: 'Topdrive',
        age: 76
    },
    {
        id: 5,
        first_name: 'Muire',
        last_name: 'Pothecary',
        email: 'mpothecary4@mit.edu',
        gender: 'Female',
        ip_address: '82.151.63.26',
        title: 'Honorable',
        job_title: 'Executive Secretary',
        race: 'Chickasaw',
        company: 'Realbridge',
        age: 15
    },
    {
        id: 6,
        first_name: 'Mano',
        last_name: 'Gwatkins',
        email: 'mgwatkins5@auda.org.au',
        gender: 'Male',
        ip_address: '134.244.218.162',
        title: 'Ms',
        job_title: 'Automation Specialist IV',
        race: 'Vietnamese',
        company: 'InnoZ',
        age: 23
    },
    {
        id: 7,
        first_name: 'Frederica',
        last_name: 'Shackleton',
        email: 'fshackleton6@examiner.com',
        gender: 'Female',
        ip_address: '191.141.61.25',
        title: 'Honorable',
        job_title: 'Help Desk Operator',
        race: 'Yuman',
        company: 'Yoveo',
        age: 89
    },
    {
        id: 8,
        first_name: 'Garvey',
        last_name: 'Islep',
        email: 'gislep7@nps.gov',
        gender: 'Male',
        ip_address: '101.45.75.228',
        title: 'Mr',
        job_title: 'Internal Auditor',
        race: 'Cambodian',
        company: 'Livefish',
        age: 76
    },
    {
        id: 9,
        first_name: 'Aristotle',
        last_name: 'Gozard',
        email: 'agozard8@exblog.jp',
        gender: 'Male',
        ip_address: '87.43.196.133',
        title: 'Rev',
        job_title: 'Software Test Engineer IV',
        race: 'Chippewa',
        company: 'Feedspan',
        age: 34
    },
    {
        id: 10,
        first_name: 'Bryon',
        last_name: 'Boulder',
        email: 'bboulder9@parallels.com',
        gender: 'Male',
        ip_address: '251.50.80.89',
        title: 'Honorable',
        job_title: 'Senior Editor',
        race: 'Argentinian',
        company: 'Kazu',
        age: 25
    }
];
